name: Build Android APK

on:
  push:
    paths:
      - '**/*.java'
      - '**/*.xml'
      - '**/build.gradle'
      - '**/AndroidManifest.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build APK
        run: |
          ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-apk
          path: app/build/outputs/apk/debug/app-debug.apk
